apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: 522449034560.dkr.ecr.eu-west-2.amazonaws.com/net-backend:{{ .Values.deployment.image.tag }}
          ports:
            - containerPort: {{ .Values.deployment.cport }}
          env:
           - name: {{ .Values.deployment.constr.name }}
             valueFrom:
               secretKeyRef:
                   name: {{ .Values.deployment.constr.secret.name }}
                   key: {{ .Values.deployment.constr.secret.key }}
